### PR TITLE
Pingread

### PR DESCRIPTION
**Pull request by sesh-kebab**
pingRead implementation as a result of discussion started on the johnny-five issue842.

Interacting with an ultrasonic sensor requires timing pulses to 10 microseconds and measuring the response to microsecond accuracy. To enable this, created a new native node plugin raspi-sonar. This pull request is to add a dependency to raspi-sonar to allow implementation of the pingRead method of the io-plugin interface.

New PR based on the instructions specified at this PR [PR 48](https://github.com/nebrius/raspi-io/pull/48)

### CODE REVIEW

**Comment by nebrius** [comment]
Thanks for the updated PR! Now it's my turn to be swamped (MS Build is this week, and I'm helping run the Node.js booth), but I hope to get to this PR this weekend/early next week

**Comment by nebrius** [comment]
Can you do a rebuild? This is in the current `lib/index.js`:

```
<<<<<<< HEAD
=======
var _raspiSonar = require('raspi-sonar');

// Hacky quick Symbol polyfill, since es6-symbol refuses to install with Node 0.10 from http://node-arm.herokuapp.com/
if (typeof global.Symbol != 'function') {
  global.Symbol = function (name) {
    return '__$raspi_symbol_' + name + '_' + Math.round(Math.random() * 0xFFFFFFF) + '$__';
  };
}

>>>>>>> Added pingRead implementation.
```

**Comment by achorein** [comment]
Hello, 
What about this PR @sesh-kebab. 
Great job was already done here, can't wait to get it works natively in J5 :)

**Comment by sesh-kebab** [comment]
hey @achorein sorry - moved continents since I submitted this PR so been inactive for a while; but all settled in now. The work is already done - just have to get the merge request right. Will get my RaspberryPi running again and start looking at this from tomorrow.

**Pull request closed without merging**
